### ISSUE TITLE
Why is this needed?

### ISSUE THREAD

**Issue by wooorm** [servinlp/cssttr#10]
https://github.com/servinlp/cssttr/blob/dd3f92f11a4d32ddaefe1c7446b4051555213226/styles.css#L130-L132

**Comment by wooorm** [comment]
And what‘s up with this?

https://github.com/servinlp/cssttr/blob/dd3f92f11a4d32ddaefe1c7446b4051555213226/styles.css#L209-L211

**Comment by servinlp** [comment]
Removed in
dd3f92f
